In [1]:
import numpy as np
X = np.array(([2, 9], [1, 5], [3, 6],[5,4]), dtype=float)
Y = np.array(([92], [86], [89],[90]), dtype=float)
y = Y/100

In [2]:
m,n=np.shape(Y)
print(m)
print(n)

4
1


In [3]:
print(X)

[[2. 9.]
 [1. 5.]
 [3. 6.]
 [5. 4.]]


In [4]:
print(y)

[[0.92]
 [0.86]
 [0.89]
 [0.9 ]]


In [5]:
#Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

In [6]:
#Derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x * (1 - x)

In [7]:
#Variable initialization
epoch=1000000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = 2 #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

In [8]:
#weight and bias initialization
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

In [9]:
print(wh)

[[0.49949691 0.82867876 0.64071888]
 [0.89409391 0.66555029 0.56089763]]


In [10]:
print(bh)

[[0.92243682 0.93726592 0.42942213]]


In [11]:
print(wout)

[[0.41804029]
 [0.6438523 ]
 [0.96521049]]


In [12]:
print(bout)

[[0.61534017]]


In [13]:
for i in range(epoch):
#Forward Propogation # Dot product + bias
    h_ip=np.dot(X,wh) + bh
    h_act = sigmoid(h_ip) # Activation function
    o_ip=np.dot(h_act,wout) + bout
    output = sigmoid(o_ip)
    #Backpropagation
    # Error at Output layer # Error at o/p
    
    
    Eo = y-output
    outgrad = derivatives_sigmoid(output)
    d_output = Eo* outgrad # Errj=Oj(1-Oj)(Tj-Oj)
    # Error at Hidden later # .T means transpose
    Eh = d_output.dot(wout.T)
    hiddengrad = derivatives_sigmoid(h_act) # How much hidden layer wts contributed to error
    d_hidden = Eh * hiddengrad # Dotproduct of nextlayererror and currentlayerop
    wout += h_act.T.dot(d_output) *lr
    wh += X.T.dot(d_hidden) *lr

In [14]:
print(wh)

[[0.50243453 0.76296167 0.25187631]
 [0.90559366 0.3472017  0.13861554]]


In [15]:
print(wout)

[[-0.40704552]
 [ 0.07428464]
 [ 2.10349938]]


In [19]:
print("Normalized Input: \n" + str(X))
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" ,output)

Normalized Input: 
[[2. 9.]
 [1. 5.]
 [3. 6.]
 [5. 4.]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]
 [0.9 ]]
Predicted Output: 
 [[0.89773634]
 [0.87654295]
 [0.89461761]
 [0.89884683]]
