In [2]:
import numpy as np
X=np.array(([2,9],[1,5],[3,6],[5,4]),dtype=float)
Y=np.array(([92],[86],[89],[90]),dtype=float)
def sigmoid(x):
    return 1/(1+np.exp(-x))
def derivatives_sigmoid(x):
    return x*(1-x)
epoch=100000
lr=0.1
inputlayer_neurons=2
hiddenlayer_neurons=3
output_neurons=1
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))
print(wh)
print(bh)
print(wout)
print(bout)
for i in range(epoch):
    h_ip=np.dot(X,wh)+bh
    h_act=sigmoid(h_ip)
    o_ip=np.dot(h_act,wout)+bout
    output=sigmoid(o_ip)
    Eo=y-output
    outgrad=derivatives_sigmoid(output)
    d_output=Eo*outgrad
    Eh=d_output.dot(wout.T)
    hiddengrad=derivatives_sigmoid(h_act)
    d_hidden=Eh*hiddengrad
    wout+=h_act.T.dot(d_output)*lr
    wh+=X.T.dot(d_hidden)*lr
print(wh)
print(wout)
print("normalized input:\n"+str(X))
print("actual output:\n" +str(y))
print("Predicated Output:\n",+output)

[[0.36539323 0.30791846 0.9663703 ]
 [0.46530192 0.11295358 0.57473813]]
[[0.66037058 0.75612618 0.89160892]]
[[0.08429016]
 [0.63507327]
 [0.12614351]]
[[0.67593141]]
[[0.22642667 0.2774122  0.98465829]
 [0.1317495  0.11794243 0.6625711 ]]
[[ 0.88362752]
 [ 1.47672381]
 [-0.66894323]]
normalized input:
[[2. 9.]
 [1. 5.]
 [3. 6.]
 [5. 4.]]
actual output:
[[0.92]
 [0.86]
 [0.89]
 [0.9 ]]
Predicated Output:
 [[0.89668109]
 [0.87787603]
 [0.89460946]
 [0.89913876]]
